// Auto-generated by @miniprogram-icons/generate — DO NOT EDIT
import { createIcon } from '../create-icon';

export const ChartNoAxesColumnDecreasing = /*#__PURE__*/ createIcon("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"> <path d=\"M5 21V3\" /> <path d=\"M12 21V9\" /> <path d=\"M19 21v-6\" /></svg>", "ChartNoAxesColumnDecreasing");
