// Auto-generated by @miniprogram-icons/generate — DO NOT EDIT
import { createIcon } from '../create-icon';

export const SmartphoneCharging = /*#__PURE__*/ createIcon("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"> <rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" /> <path d=\"M12.667 8 10 12h4l-2.667 4\" /></svg>", "SmartphoneCharging");
