import * as fs from 'node:fs'
import * as path from 'node:path'

import type { IconDefinition } from '../types'
import { fail } from '../utils/args'
import { ensureDir, findWorkspaceRoot } from '../utils/fs'
import { generateIconModule, generateIndexFile, kebabToPascal } from '../utils/icons'

export async function generateIcons(packageDir: string) {
  const workspaceRoot = findWorkspaceRoot(packageDir)
  const iconsSourceDir = path.join(workspaceRoot, '.lucide-cache', 'icons')
  const outputDir = path.join(packageDir, 'src', 'icons')
  const indexFile = path.join(packageDir, 'src', 'index.ts')

  if (!fs.existsSync(iconsSourceDir)) {
    fail('Icons source directory not found. Run fetch-icons first.')
  }

  fs.rmSync(outputDir, { recursive: true, force: true })
  ensureDir(outputDir)

  const svgFiles = fs.readdirSync(iconsSourceDir).filter(file => file.endsWith('.svg'))
  const icons: IconDefinition[] = []

  for (const file of svgFiles) {
    const name = file.replace('.svg', '')
    const componentName = kebabToPascal(name)
    const svgPath = path.join(iconsSourceDir, file)
    const svgContent = fs.readFileSync(svgPath, 'utf8')

    icons.push({ name, componentName, svgContent })
    fs.writeFileSync(
      path.join(outputDir, `${name}.ts`),
      generateIconModule({ name, componentName, svgContent }),
    )
  }

  fs.writeFileSync(indexFile, generateIndexFile(icons))

  const iconListContent = `// Auto-generated by @miniprogram-icons/generate — DO NOT EDIT\nexport const iconList = ${JSON.stringify(
    icons.map(icon => ({
      name: icon.name,
      componentName: icon.componentName,
    })),
    null,
    2,
  )} as const;\n`

  for (const cliPackageName of ['miniprogram-icons-find', 'miniprogram-icons-show']) {
    const targetDir = path.join(workspaceRoot, 'packages', cliPackageName, 'src')
    ensureDir(targetDir)
    fs.writeFileSync(path.join(targetDir, 'icon-list.ts'), iconListContent)
  }

  console.log(`Generated ${icons.length} icon modules`)
}
