import type { IconDefinition } from '../types'

export const LUCIDE_REPO = 'https://github.com/lucide-icons/lucide.git'

export function kebabToPascal(value: string) {
  return value
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

export function escapeSvgForJs(svgContent: string) {
  return svgContent
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '')
    .replace(/\r/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

export function generateIconModule(icon: IconDefinition) {
  const escaped = escapeSvgForJs(icon.svgContent)

  return `// Auto-generated by @miniprogram-icons/generate — DO NOT EDIT
import { createIcon } from '../create-icon';

export const ${icon.componentName} = /*#__PURE__*/ createIcon("${escaped}", "${icon.componentName}");
`
}

export function generateIndexFile(icons: IconDefinition[]) {
  const iconExports = icons
    .map(icon => {
      const escaped = escapeSvgForJs(icon.svgContent)
      return `export const ${icon.componentName} = /*#__PURE__*/ createIcon("${escaped}", "${icon.componentName}");`
    })
    .join('\n')

  return `// Auto-generated by @miniprogram-icons/generate — DO NOT EDIT
import { createIcon } from './create-icon';
export { createIcon };
export { MiniProgramIconsProvider } from './context';
export type { IconProps, MiniProgramIconsConfig } from './types';
export type { MiniProgramIconsProviderProps } from './context';

${iconExports}
`
}
